---
# 👇 Playbook의 시작은 반드시 대시(-)로 시작해야 합니다.
- name: Web Server Setup Playbook
  hosts: localhost
  connection: local

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
# 👇 Task 목록도 대시(-)로 시작해야 합니다.
    - name: Create a test file in the home directory
      ansible.builtin.file:
        path: ~/ansible_test_ok.txt
        state: touch
        mode: '0644'